# Changes here will be overwritten by Copier
_commit: 1.4.0
_src_path: gh:pawamoy/copier-uv
author_email: dev@pawamoy.fr
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2024'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: dev@pawamoy.fr
copyright_license: ISC License
insiders: true
insiders_email: insiders@pawamoy.fr
insiders_repository_name: griffe-public-wildcard-imports
project_description: Mark wildcard imported objects as public.
project_name: griffe-public-wildcard-imports
public_release: false
python_package_command_line_name: ''
python_package_distribution_name: griffe-public-wildcard-imports
python_package_import_name: griffe_public_wildcard_imports
repository_name: griffe-public-wildcard-imports
repository_namespace: mkdocstrings
repository_provider: github.com

